#!/bin/bash
# Basic build script

# Define plugs here

#plugs=( "Wallpaper" "Monitors" "Appearance" )


echo "Compiling switchboard itself"
valac *.vala --pkg unique-1.0 --pkg gee-1.0 --pkg glib-2.0 --pkg gio-2.0 --pkg gtk+-2.0 --pkg gdk-2.0 -o switchboard | grep "succeeded"
echo "Finished compiling switchboard itself"

echo "Now compiling plugs"
for i in "${plugs[@]}"
do
   cd plug
   ./compile $i
   cd -
done
echo "Finished compiling plugs"
