#!/bin/bash
# Basic build script
if [ -z $1 ]
  then
    echo -e "The first argument needs to be the name of the vala file \n(exactly as it is named) that you want to compile."
    exit
  else
    echo "Building $1"
    valac $1.vala Color.vala Utilities.vala ElementarySearchBar.vala SettingsPlug.vala log.vala AppMenu.vala ToolButtonWithMenu.vala --pkg gee-1.0 --pkg glib-2.0 --pkg gtk+-2.0 --pkg gconf-2.0 --pkg gdk-2.0 -o $1
    echo "Finished building $1"
fi
