name: Gettext Updates

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: elementary/docker:next-unstable

    steps:
    - name: Install git
      run: |
        apt-get update
        apt-get install git -y

    - name: Clone repository
<<<<<<< HEAD
      uses: actions/checkout@v4
=======
      uses: actions/checkout@v3
>>>>>>> b013b28 (actions/checkout@v3 (#254))
      with:
        token: ${{ secrets.GIT_USER_TOKEN }}

    - name: Update Translation Files
      uses: elementary/actions/gettext-template@next
      env:
        GIT_USER_TOKEN: ${{ secrets.GIT_USER_TOKEN }}
        GIT_USER_NAME: "elementaryBot"
        GIT_USER_EMAIL: "builds@elementary.io"
